### ISSUE TITLE
Fairseq breaks AbLang installation with python > 3.8

### ISSUE THREAD

**Issue by ElArkk** [oxpig/AbLang#1]
See issue here: https://github.com/pytorch/fairseq/issues/3535

Using Python 3.8.12 I was able to install ablang via pip, but Python 3.9 and 3.10 leads to the error described in the issue linked above.

**Comment by sdvillal** [comment]
For conda users, there are a few open PRs aiming at fixing this. In particular [this one](https://github.com/conda-forge/fairseq-feedstock/pull/17) seems to work.

Until they get accepted, a workaround is to use ```sdvillal::fairseq``` as a dependency in your environment (linux and macos only).

**Comment by TobiasHeOl** [comment]
Sorry for the long wait! fairseq keeps introducing different dependency issues. To resolve this, we have decided to extract the code from fairseq that we use, allowing us not to install fairseq anymore [8f901e9](https://github.com/oxpig/AbLang/commit/8f901e99fd0ec6cedf12204f89b1de2cc76edbd4).
