### ISSUE TITLE
Downloading model fails: opig.stats.ox.ac.uk is unreachable

### ISSUE THREAD

**Issue by maximz** [oxpig/AbLang#10]
Dear AbLang team,

I'm unable to download the model because requests to opig.stats.ox.ac.uk are timing out:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='opig.stats.ox.ac.uk', port=443): Max retries exceeded with url: /data/downloads/ablang-heavy.tar.gz
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f961c4e7160>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

I first experienced this issue about 24 hours ago. Tried again today, but no luck. Thank you!

**Comment by FBoyles** [comment]
Our web server is currently down for maintenence. We expect it to be back online later today. For updates on server status, you can follow us on twitter: https://twitter.com/OPIGlets

**Comment by maximz** [comment]
Thank you, @FBoyles. Looks like this is working again.
