### ISSUE TITLE
Does the mode "likelihood" mode predict probabilities for insertions as well? 

### ISSUE THREAD

**Issue by tsjain** [oxpig/AbLang#5]
From the notebook, and running the model internally, it doesn't appear that the probability of an insertion is returned by the model. 
Is that intentional? 

For certain sequences, the most likely solution could be an insertion instead of an amino-acid.

**Comment by TobiasHeOl** [comment]
Hi tsjain,

You are right, the current model does not predict indels. An alternative approach is to randomly insert masks manually into the sequence as insertions.

I hope this helps!

Best,
Tobias
