### ISSUE TITLE
Clarification Question

### ISSUE THREAD

**Issue by fergusonscripps** [oxpig/AbLang#8]
Cool code trying it for a few things in the lab.

For the "Residue likelihood" I wanted to check. The first and last probabilitiy arrays are the SOS and EOS and do not correspond to a "real" amino acid residue?

Are the probabilities in alphabetical for the 20 essential amino acids?

**Comment by TobiasHeOl** [comment]
Thanks! You are correct that the output also returns the vector of likelihoods for SOS and EOS (not real aa's), however; the vector of likelihoods for each position only contain values for the 20 aa's. This was a design choice based on how we are using the model. 

The likelihoods are not ordered alphabetically, but you can view the order with the following:

`
print(model.tokenizer.vocab_to_aa)
`
I hope this answers your questions!
